add multi modules dirs

diff --git a/wildenv-hook b/wildenv-hook
--- a/wildenv-hook
+++ b/wildenv-hook
@@ -3,11 +3,30 @@
 export WILDENV_ROOT_DIR=${WILDENV_ROOT_DIR:-$HOME/.wildenv}
 WILDENV_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
 
+export WILDENV_MODULES_DIRS=${WILDENV_MODULES_DIRS:-"${WILDENV_SCRIPT_DIR}/modules"}
+export WILDENV_MODULES=${WILDENV_MODULES:-shelltools:kubernetes}
+
 if [[ ! -d "${WILDENV_ROOT_DIR}" ]]; then
   echo "Wildenv not configured !"
 else
-  export PATH="${WILDENV_ROOT_DIR}/bin:$PATH"
-  for module in shelltools kubernetes; do
-    . "${WILDENV_SCRIPT_DIR}/modules/${module}/bashrc.sh"
+  if ! [[ "$PATH" =~ "${WILDENV_ROOT_DIR}/bin" ]]; then
+    export PATH="${WILDENV_ROOT_DIR}/bin:$PATH"
+  fi
+
+  IFS=':' read -r -a _modules <<< "${WILDENV_MODULES}"
+  IFS=':' read -r -a _modules_dirs <<< "${WILDENV_MODULES_DIRS}"
+
+  for _module in "${_modules[@]}"; do
+    _module_found=1
+    for _modules_dir in "${_modules_dirs[@]}"; do
+      if [[ -d "${_modules_dir}/${_module}" ]]; then
+        . "${_modules_dir}/${_module}/bashrc.sh"
+        _module_found=0
+        break
+      fi
+    done
+    if [[ $_module_found -eq 1 ]]; then
+      printf 'Module %s not found.\n' $_module
+    fi
   done
 fi
